baseURL = "https://pavel.oborin.me"
languageCode = "ru-RU"
title = "Pavel Oborin"
theme = "minimal"
tags = ["tags", "categories"]
publishDir = "."
builddrafts = true
canonifyurls = false
contentdir = "content"
layoutdir = "layouts"
googleAnalytics = "UA-116728151-1"
[params]
    author = ""
    description = "HEY. GLAD YOU'RE HERE!<br/> My name is Pavel Oborin, I am a back-end web developer and this is my space"
    githubUsername = "paveloborin"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Open Sans" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["php","go", "shell", "haskell", "bash"]
    authorimage = 'headshot.png'

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
 url = "https://github.com/paveloborin"
    name = "GITHUB"
    weight = 3

[[menu.main]]
 url = "https://www.visualcv.com/pavel-oborin"
    name = "CV"
    weight = 4

[[menu.main]]
    url = "/just-for-fan/"
    name = "Just For fans"
    weight = 5

[[menu.main]]
    url = "/publications/list"
    name = "My Publications"
    weight = 6


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@pavel.oborin.me"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/paveloborin"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/pavel-oborin/"
    name = "linkedin"
    weight = 3

[[menu.icon]]
    url = "https://scholar.google.ru/citations?user=sR8RU10AAAAJ"
    name = "graduation-cap"
    weight = 5
